server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-5156434.okta.com/oauth2/default
    client-id: 0oa19lrfh3arJGUG05d7
    client-secret: tVUjjPNsaeIQzmxaso_yG75eMUmaRgaLXP1XrGQn
spring:
  thymeleaf:
    cache: false
